# Training data
data:
  db_name: "attica_traffic"       
  schema_name: "prod"
  table_name: "mrt_traffic_road"          
  test_size: 0.2
  random_state: 42
  lookback: 365 # how many days back the training data look

# Model hyperparameters
model:
  max_iter: 500
  max_depth: 15
  max_leaf_nodes: 255
  learning_rate: 0.05
  min_samples_leaf: 500
  # Note: ColumnTransformer puts transformed columns first. 
  # Index 0 will be the Target-Encoded device_id (continuous).
  # Index 1 will be the Ordinal-Encoded road_name (categorical).
  categorical_features: [1]

# mlflow
mlflow:
  model_name: 'attica_traffic_model'
  experiment_name: 'ml_model_traffic_speed_prediction'

# Drift reporting
drift:
  mlflow_monitor_experiment_name: 'data_drift_monitoring'
  sample_size: 100000 # how many rows are saved to mlflow for use as "reference"
  lookback: 14 # how many days back the "current" monitoring data look