[project]
name = "attica-traffic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair<5",
    "category-encoders>=2.9.0",
    "dagshub>=0.6.8",
    "dbt-duckdb>=1.10.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.133.0",
    "hf-transfer>=0.1.9",
    "holidays>=0.91",
    "httpx>=0.28.1",
    "huggingface-hub>=1.4.1",
    "loguru>=0.7.3",
    "mlflow>=3.10.0",
    "pandas<3",
    "polars>=1.38.1",
    "pyaml>=26.2.1",
    "pyarrow>=23.0.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "streamlit>=1.35.0",
    "tenacity>=9.1.4",
]
