# transform/dbt_project.yml
name: 'attica_traffic'
version: '1.0.0'
config-version: 2

# This MUST match the name in profiles.yml
profile: 'attica_traffic'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

# Standard Medallion Materialization
models:
  attica_traffic:
    staging:
      +materialized: table      # We materialize as tables to download data once and stop hitting the HF API.
    intermediate:
      +materialized: view
    marts:
      +materialized: table     # Marts should be physical tables
      reporting:
        +materialized: table